services:
  whoami:
    image: traefik/whoami
    restart: unless-stopped
    networks:
      - crest-web
    labels:
      caddy: whoami.crest.internal
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal

networks:
  crest-web:
    external: true
